language: ruby
rvm: system
os: osx

matrix:
  include:
    - env: OSX=10.11
      compiler: clang
      osx_image: xcode8
    - env: OSX=10.12
      compiler: clang
      osx_image: xcode9.2

cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle

branches:
  only:
    - test

before_install:
  - sudo chown -R "$USER" "$(brew --repo)"
  - travis_retry brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  # - sudo mkdir -p /usr/local/var/homebrew/linked
  # - sudo chown -R $(whoami) /usr/local/var/homebrew/linked
  - if [ "$OSX" == '10.11' ]; then
      brew cask reinstall xquartz;
    fi

script:
  - brew test-bot
